### ISSUE TITLE
Question: Any know bug with this version?

### ISSUE THREAD

**Issue by nmocruz** [Appendme/android_device_lenovo_x2#3]
Hi,
Any know bug with this version?
It's possible to update the list of problems with this?

**Comment by Appendme** [comment]
Wifi(+hotspot), bt, sound(only headphones), sensors. 
Because of studying at the university, I do not have much time to work on the firmware. 
I think to go back to 12.1, since the device with installed "GAPPS" starts to slow down strongly. And the problem with "EGL_BAD_DISPLAY" is still not solved - https://gist.github.com/Appendme/e44cdad28fba83146e04ff5a1a566399
